node {
    stage('One: Variables'){
        // Stage one of a scripted Jenkins pipeline
        echo "Stage one starting..."
        // echo 'This is build number $currentBuild.number.'
        echo "This is build number $currentBuild.number."
        // echo 'This is build number ${currentBuild.number}.'
        echo "This is build number ${currentBuild.number}."
        // echo 'This is build number currentBuild.number'
        // echo "This is build number currentBuild.number"
        // echo currentBuild.number
        echo "Your favorite singer is ${params.favorite_singer}."
        echo "Your favorite singer is $params.favorite_singer."
        echo "Workspace: $WORKSPACE"
        echo 'Current directory:'
        pwd() 
        echo "Stage one ending..."
    }
    stage('Two: Deployment validation'){
        // Stage two of a scripted Jenkins pipeline
        echo "Stage two starting..."
        input message: 'Keep going ?', ok: 'Yes, keep running this pipeline.'
        echo "Stage two ending..."
    }
    stage('Three: Conditions'){
        // Stage three of a scripted Jenkins pipeline
        echo "Stage three starting..."
        if (params.favorite_singer == 'Lady Gaga') {
            echo "Oh, I see you like Lady Gaga..."
        } else {
            echo "I also like ${params.favorite_singer}"
        }
        if (isUnix()) {
            echo "This pipeline is running on a UNIX-like node."
        }
        echo "Stage three ending..."
    }
}
